apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ template "helm-chart.fullname" . }}-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ template "helm-chart.fullname" . }}-pod
    template:
        metadata:
            labels:
                app: {{ template "helm-chart.fullname" . }}-pod
        spec:
            imagePullSecrets:
            -   name: myregistrykey
            containers:
            -   name: {{ .Values.podContainerName }}
                image: {{ .Values.dockerImage }}
                imagePullPolicy: {{ .Values.imagePullPolicy }}
                env:
                -   name: BROKER_SERVICE_URL
                    value: {{ .Values.brokerServiceUrl }}
                -   name: PULSAR_TEXT_EMBEDDING_TOPIC
                    value: {{ .Values.pulsarTextEmbeddingTopic }}
                -   name: SUBSCRIPTION_NAME
                    value: {{ .Values.subscriptionName }}


---

apiVersion: v1
kind: Service
metadata:
    name: {{ template "helm-chart.fullname" . }}-service
spec:
    type: NodePort
    selector:
        name: {{ template "helm-chart.fullname" . }}-pod
    ports:
        - port: 80
          targetPort: 1001

---

apiVersion: v1
kind: Secret
metadata:
    name: myregistrykey
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: {{ template "imagePullSecret" . }}