#####################
# Messaging Service #
#####################
# Pulsar service URL. See some old documentation for the url:
# http://pulsar.apache.org/docs/v1.19.0-incubating/deployment/Kubernetes/
brokerServiceUrl: pulsar://pulsar-mini-broker.pulsar.svc.cluster.local:6650/
#
pulsarTextTopic: apache/pulsar/text-topic
pulsarTextEmbeddingTopic: apache/pulsar/text-embedding-topic
subscriptionName: mapping-svc

# Docker
# dockerImage: temdy/text-embedding:v0.1.1
podContainerName: mapping
imagePullPolicy: Always

deployment:
    is_dev: false

# ## There is a secret-values.yaml file with these secrets,
# ## but I .gitignore it
# ##
# imageCredentials:
#   registry: docker.io
#   username: *****
#   password: *****
#   email: *****@gmail.com

db:
    driver: postgresql
    user: sunnyday1
    host: postgresql.db
    port: 5432
    databasename: aab-goosht
