apiVersion: v1
kind: ConfigMap
metadata:
    name: storage-config
data:
    DB_DRIVER: "{{ .Values.db.driver }}"
    DB_USER: "{{ .Values.db.user }}"
    DB_PASSWORD: "{{ .Values.secrets.db.password }}"
    DB_HOST: "{{ .Values.db.host }}"
    DB_PORT: "{{ .Values.db.port }}"
    DB_DATABASENAME: "{{ .Values.db.databasename }}"
    CACHE_HOST: "{{ .Values.cache.host }}"
    CACHE_PORT: "{{ .Values.cache.port }}"
    K8S_READINESS_PROBE_FILE: "{{ .Values.deployment.readinessProbeFile }}"


---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ template "helm-chart.fullname" . }}-web-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ template "helm-chart.fullname" . }}-web-pod
    template:
        metadata:
            labels:
                app: {{ template "helm-chart.fullname" . }}-web-pod
            annotations:
                timestamp: "{{ date "20060102150405" .Release.Time }}"
        spec:
            imagePullSecrets:
            -   name: {{ template "helm-chart.fullname" . }}-registrykey
            containers:
            -   name: {{ .Values.podContainerName }}-web-server
                image: {{ .Values.dockerImage }}
                imagePullPolicy: {{ .Values.imagePullPolicy }}
                command: ["gunicorn"]
                args: ["route:app", "-c", "configs/gunicorn_configs.py", "--preload"]
                envFrom:
                    - configMapRef:
                        name: storage-config
                env:
                -   name: BROKER_SERVICE_URL
                    value: {{ .Values.brokerServiceUrl }}
                -   name: PULSAR_TASK_TOPIC
                    value: {{ .Values.pulsarTaskTopic }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ template "helm-chart.fullname" . }}-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ template "helm-chart.fullname" . }}-pod
    template:
        metadata:
            labels:
                app: {{ template "helm-chart.fullname" . }}-pod
            annotations:
                timestamp: "{{ date "20060102150405" .Release.Time }}"
        spec:
            imagePullSecrets:
            -   name: {{ template "helm-chart.fullname" . }}-registrykey
            containers:
            -   name: {{ .Values.podContainerName }}-consumer-raw-text
                image: {{ .Values.dockerImage }}
                imagePullPolicy: {{ .Values.imagePullPolicy }}
                command: ["python"]
                args: ["consumers/raw_text.py"]
                env:
                -   name: SUBSCRIPTION_NAME
                    value: {{ .Values.subscriptionName }}
                -   name: BROKER_SERVICE_URL
                    value: {{ .Values.brokerServiceUrl }}
                -   name: PULSAR_TEXT_TOPIC
                    value: {{ .Values.pulsarTextTopic }}
                # -   name: PULSAR_TEXT_EMBEDDING_TOPIC
                #     value: {{ .Values.pulsarTextEmbeddingTopic }}
                envFrom:
                    - configMapRef:
                        name: storage-config
            -   name: {{ .Values.podContainerName }}-consumer-text-embedding
                image: {{ .Values.dockerImage }}
                imagePullPolicy: {{ .Values.imagePullPolicy }}
                command: ["python"]
                args: ["consumers/text_embedding.py"]
                env:
                -   name: SUBSCRIPTION_NAME
                    value: {{ .Values.subscriptionName }}
                -   name: BROKER_SERVICE_URL
                    value: {{ .Values.brokerServiceUrl }}
                # -   name: PULSAR_TEXT_TOPIC
                #     value: {{ .Values.pulsarTextTopic }}
                -   name: PULSAR_TEXT_EMBEDDING_TOPIC
                    value: {{ .Values.pulsarTextEmbeddingTopic }}
                envFrom:
                    - configMapRef:
                        name: storage-config
            -   name: {{ .Values.podContainerName }}-consumer-task
                image: {{ .Values.dockerImage }}
                imagePullPolicy: {{ .Values.imagePullPolicy }}
                command: ["python"]
                args: ["consumers/task.py"]
                env:
                -   name: SUBSCRIPTION_NAME
                    value: {{ .Values.subscriptionName }}
                -   name: BROKER_SERVICE_URL
                    value: {{ .Values.brokerServiceUrl }}
                -   name: PULSAR_TEXT_TOPIC
                    value: {{ .Values.pulsarTextTopic }}
                -   name: PULSAR_TASK_TOPIC
                    value: {{ .Values.pulsarTaskTopic }}
                -   name: GOOGLE_API_KEY
                    value: "{{ .Values.secrets.google.api_key }}"
                envFrom:
                    - configMapRef:
                        name: storage-config
                readinessProbe:
                    exec:
                        command:
                        - cat
                        - {{ .Values.deployment.readinessProbeFile }}
                    initialDelaySeconds: 2
                    periodSeconds: 3


---

# apiVersion: v1
# kind: Service
# metadata:
#     name: {{ template "helm-chart.fullname" . }}-proxy-service
# spec:
#     type: LoadBalancer
#     selector:
#         app: {{ template "helm-chart.fullname" . }}-web-pod
#     ports:
#         - port: {{ .Values.webServerPort }}
#           targetPort: {{ .Values.webServerPort }}

# ---

apiVersion: v1
kind: Service
metadata:
    name: {{ template "helm-chart.fullname" . }}-service
spec:
    type: NodePort
    selector:
        app: {{ template "helm-chart.fullname" . }}-web-pod
    ports:
        - port: {{ .Values.webServerPort }}
          targetPort: {{ .Values.webServerPort }}

---

apiVersion: v1
kind: Secret
metadata:
    name: {{ template "helm-chart.fullname" . }}-registrykey
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: {{ template "imagePullSecret" . }}
