apiVersion: v1
kind: ConfigMap
metadata:
    name: db-config
data:
    DB_DRIVER: "{{ .Values.db.driver }}"
    DB_USER: "{{ .Values.db.user }}"
    DB_PASSWORD: "{{ .Values.secrets.db.password }}"
    DB_HOST: "{{ .Values.db.host }}"
    DB_PORT: "{{ .Values.db.port }}"
    DB_DATABASENAME: "{{ .Values.db.databasename }}"

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ template "helm-chart.fullname" . }}-web-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ template "helm-chart.fullname" . }}-web-pod
    template:
        metadata:
            labels:
                app: {{ template "helm-chart.fullname" . }}-web-pod
        spec:
            imagePullSecrets:
            -   name: {{ template "helm-chart.fullname" . }}-registrykey
            containers:
            -   name: {{ .Values.podContainerName }}-web-server
                image: {{ .Values.dockerImage }}
                imagePullPolicy: {{ .Values.imagePullPolicy }}
                command: ["gunicorn"]
                args: ["route:app", "-c", "configs/gunicorn_configs.py"]
                envFrom:
                    - configMapRef:
                        name: db-config
                # env:
                # -   name: DB_DRIVER
                #     value: "{{ .Values.db.driver }}"
                # -   name: DB_USER
                #     value: "{{ .Values.db.user }}"
                # -   name: DB_PASSWORD
                #     value: "{{ .Values.secrets.db.password }}"
                # -   name: DB_HOST
                #     value: "{{ .Values.db.host }}"
                # -   name: DB_PORT
                #     value: "{{ .Values.db.port }}"
                # -   name: DB_DATABASENAME
                #     value: "{{ .Values.db.databasename }}"

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ template "helm-chart.fullname" . }}-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ template "helm-chart.fullname" . }}-pod
    template:
        metadata:
            labels:
                app: {{ template "helm-chart.fullname" . }}-pod
        spec:
            imagePullSecrets:
            -   name: {{ template "helm-chart.fullname" . }}-registrykey
            containers:
            -   name: {{ .Values.podContainerName }}-consumer-raw-text
                image: {{ .Values.dockerImage }}
                imagePullPolicy: {{ .Values.imagePullPolicy }}
                command: ["python"]
                args: ["consumers/raw_text.py"]
                env:
                -   name: BROKER_SERVICE_URL
                    value: {{ .Values.brokerServiceUrl }}
                -   name: PULSAR_TEXT_TOPIC
                    value: {{ .Values.pulsarTextTopic }}
                -   name: PULSAR_TEXT_EMBEDDING_TOPIC
                    value: {{ .Values.pulsarTextEmbeddingTopic }}
                -   name: SUBSCRIPTION_NAME
                    value: {{ .Values.subscriptionName }}
                -   name: DB_DRIVER
                    value: "{{ .Values.db.driver }}"
                -   name: DB_USER
                    value: "{{ .Values.db.user }}"
                -   name: DB_PASSWORD
                    value: "{{ .Values.secrets.db.password }}"
                -   name: DB_HOST
                    value: "{{ .Values.db.host }}"
                -   name: DB_PORT
                    value: "{{ .Values.db.port }}"
                -   name: DB_DATABASENAME
                    value: "{{ .Values.db.databasename }}"
            -   name: {{ .Values.podContainerName }}-consumer-text-embedding
                image: {{ .Values.dockerImage }}
                imagePullPolicy: {{ .Values.imagePullPolicy }}
                command: ["python"]
                args: ["consumers/text_embedding.py"]
                env:
                -   name: BROKER_SERVICE_URL
                    value: {{ .Values.brokerServiceUrl }}
                -   name: PULSAR_TEXT_TOPIC
                    value: {{ .Values.pulsarTextTopic }}
                -   name: PULSAR_TEXT_EMBEDDING_TOPIC
                    value: {{ .Values.pulsarTextEmbeddingTopic }}
                -   name: SUBSCRIPTION_NAME
                    value: {{ .Values.subscriptionName }}
                -   name: DB_DRIVER
                    value: "{{ .Values.db.driver }}"
                -   name: DB_USER
                    value: "{{ .Values.db.user }}"
                -   name: DB_PASSWORD
                    value: "{{ .Values.secrets.db.password }}"
                -   name: DB_HOST
                    value: "{{ .Values.db.host }}"
                -   name: DB_PORT
                    value: "{{ .Values.db.port }}"
                -   name: DB_DATABASENAME
                    value: "{{ .Values.db.databasename }}"
            -   name: {{ .Values.podContainerName }}-consumer-task
                image: {{ .Values.dockerImage }}
                imagePullPolicy: {{ .Values.imagePullPolicy }}
                command: ["python"]
                args: ["consumers/task.py"]
                env:
                -   name: BROKER_SERVICE_URL
                    value: {{ .Values.brokerServiceUrl }}
                -   name: PULSAR_TASK_TOPIC
                    value: {{ .Values.pulsarTaskTopic }}
                -   name: SUBSCRIPTION_NAME
                    value: {{ .Values.subscriptionName }}
                -   name: DB_DRIVER
                    value: "{{ .Values.db.driver }}"
                -   name: DB_USER
                    value: "{{ .Values.db.user }}"
                -   name: DB_PASSWORD
                    value: "{{ .Values.secrets.db.password }}"
                -   name: DB_HOST
                    value: "{{ .Values.db.host }}"
                -   name: DB_PORT
                    value: "{{ .Values.db.port }}"
                -   name: DB_DATABASENAME
                    value: "{{ .Values.db.databasename }}"
                -   name: GOOGLE_API_KEY
                    value: "{{ .Values.secrets.google.api_key }}"

---

# apiVersion: v1
# kind: Service
# metadata:
#     name: {{ template "helm-chart.fullname" . }}-proxy-service
# spec:
#     type: LoadBalancer
#     selector:
#         app: {{ template "helm-chart.fullname" . }}-web-pod
#     ports:
#         - port: {{ .Values.webServerPort }}
#           targetPort: {{ .Values.webServerPort }}

# ---

apiVersion: v1
kind: Service
metadata:
    name: {{ template "helm-chart.fullname" . }}-service
spec:
    type: NodePort
    selector:
        app: {{ template "helm-chart.fullname" . }}-web-pod
    ports:
        - port: {{ .Values.webServerPort }}
          targetPort: {{ .Values.webServerPort }}

---

apiVersion: v1
kind: Secret
metadata:
    name: {{ template "helm-chart.fullname" . }}-registrykey
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: {{ template "imagePullSecret" . }}
